// <auto-generated />
using System;
using Infrastructure.DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260217151959_Mig0InitialCreate")]
    partial class Mig0InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Concrete.Contract", b =>
                {
                    b.Property<string>("ContractId")
                        .HasColumnType("text");

                    b.Property<double>("CommissionRate")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ContractId");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Concrete.League", b =>
                {
                    b.Property<string>("LeagueId")
                        .HasColumnType("text");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeagueId");

                    b.ToTable("Leagues", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Concrete.Offer", b =>
                {
                    b.Property<string>("OfferId")
                        .HasColumnType("text");

                    b.Property<double>("CommissionRate")
                        .HasColumnType("double precision");

                    b.Property<int>("ContractPeriodMonths")
                        .HasColumnType("integer");

                    b.Property<bool>("OfferStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OfferId");

                    b.ToTable("Offers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Concrete.OwnedPlayer", b =>
                {
                    b.Property<string>("OwnedPlayerId")
                        .HasColumnType("text");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OwnedPlayerId");

                    b.ToTable("OwnedPlayers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Concrete.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<double>("MarketValue")
                        .HasColumnType("double precision");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlayerId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Concrete.Team", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text");

                    b.Property<string>("LeagueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TeamId");

                    b.ToTable("Teams", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
